apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch liveliguy; sleep 30; rm -rf liveliguy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - liveliguy
      initialDelaySeconds: 5
      periodSeconds: 5