---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oker
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: oker
  template:
    metadata:
      labels:
        app: oker
    spec:
      containers:
        - image: k8s.gcr.io/hpa-example
          name: oker
          ports:
            - containerPort: 80
          env:
            - name: CURRENT_EXERCISE_VERSION
              value: {{.Values.lesson}}
