apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simpledeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpledeployment
  template:
    metadata:
      labels:
        app: simpledeployment
    spec:
      containers:
        - name: simplepod
          image: k8s.gcr.io/hpa-example
          ports:
            - name: app
              containerPort: 80
          env:
            - name: CURRENT_EXERCISE_VERSION
              value: LESSON_5