---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: moe
spec:
  replicas: {{.Values.scale}}
  selector:
    matchLabels:
      app: moe
  template:
    metadata:
      labels:
        app: moe
    spec:
      containers:
        - image: {{.Values.image}}
          imagePullPolicy: Always
          name: moe
          env:
          - name: CURRENT_VERSION
            value: {{.Values.currentVersion}}
          - name: STOOGE
            value: I am Moe, no relation to Curly"
          ports:
            - containerPort: {{.Values.containerPort}}