---
kind: Service
apiVersion: v1
metadata:
  name: moe
spec:
  selector:
    app: moe
  ports:
    - name: main
      protocol: TCP
      port: {{.Values.servicePort}}
      targetPort: {{.Values.serviceTargetPort}}
